Vagrant.configure("2") do |config|

    config.vm.define "catalog-db" do |catalog|
        catalog.vm.box = "bento/ubuntu-16.04"
        catalog.vm.hostname = "catalog-db"
        catalog.vm.network "forwarded_port", guest: 1433, host: 1433
        catalog.vm.synced_folder "./catalog", "/provision", type: "smb"

        catalog.ssh.username = "vagrant"
        catalog.ssh.password = "vagrant"

        catalog.vm.provider "hyperv" do |h|
            h.memory = 2048
            h.vmname = "catalog-db"
        end

        catalog.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "/provision/playbook.yaml"
        end
    end

    config.vm.define "ordering-db" do |ordering|
        ordering.vm.box = "bento/ubuntu-16.04"
        ordering.vm.hostname = "ordering-db"
        ordering.vm.network "forwarded_port", guest: 9042, host: 9042
        ordering.vm.synced_folder "./ordering", "/provision", type: "smb"

        ordering.ssh.username = "vagrant"
        ordering.ssh.password = "vagrant"

        ordering.vm.provider "hyperv" do |h|
            h.memory = 2048
            h.vmname = "ordering-db"
        end

        ordering.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "/provision/playbook.yaml"
        end
    end

    config.vm.define "identity-db" do |identity|
        identity.vm.box = "bento/ubuntu-16.04"
        identity.vm.hostname = "identity-db"
        identity.vm.network "forwarded_port", guest: 5432, host: 5432
        identity.vm.synced_folder "./identity", "/provision", type: "smb"

        identity.ssh.username = "vagrant"
        identity.ssh.password = "vagrant"

        identity.vm.provider "hyperv" do |h|
            h.memory = 2048
            h.vmname = "identity-db"
        end

        identity.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "/provision/playbook.yaml"
        end
    end

end